//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication3.Resourses.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create one.
        /// </summary>
        public static string CreateOne {
            get {
                return ResourceManager.GetString("CreateOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog Feeder is aimed to let you feed your dog easily just by clicking one button in you Puppy Care mobile application.  The application will also advice you, how much food should you give to your pet according to its health parameters. Smart Feeder will also control the constant high water level in a dog’s bowl and refill it if it is a need..
        /// </summary>
        public static string DogFeeder {
            get {
                return ResourceManager.GetString("DogFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Dog Nest will allow a dog owner to control the microclimate in the dog’s sleeping place from the Puppy Care mobile application. You will be able to heat the nest a bit, when it is too cold out or cool it viсe versa..
        /// </summary>
        public static string DogNest {
            get {
                return ResourceManager.GetString("DogNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go In Your Account.
        /// </summary>
        public static string GoInAccount {
            get {
                return ResourceManager.GetString("GoInAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, .
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOff.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT laboratory
        ///Microsoft Ukraine
        ///Kyiv, Zhilyanska st. 75
        ///P: 650-555-1212
        /// F: 650-555-1213.
        /// </summary>
        public static string MicrosoftContacts {
            get {
                return ResourceManager.GetString("MicrosoftContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppy Care project was created with the help of Microsoft Ukraine Internet of Things laboratory..
        /// </summary>
        public static string MicrosoftHelp {
            get {
                return ResourceManager.GetString("MicrosoftHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul &quot;Bed&quot;.
        /// </summary>
        public static string ModulBed {
            get {
                return ResourceManager.GetString("ModulBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul &quot;Colar&quot;.
        /// </summary>
        public static string ModulColar {
            get {
                return ResourceManager.GetString("ModulColar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module &apos;Bed&apos; includes temperature sensor and able to change temperature via fan.
        /// </summary>
        public static string ModuleBadWhatCan {
            get {
                return ResourceManager.GetString("ModuleBadWhatCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul &quot;Feeder&quot;.
        /// </summary>
        public static string ModuleFeeder {
            get {
                return ResourceManager.GetString("ModuleFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account?.
        /// </summary>
        public static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your Puppy Care project account.
        /// </summary>
        public static string PCAccount {
            get {
                return ResourceManager.GetString("PCAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Account.
        /// </summary>
        public static string PersonalAccount {
            get {
                return ResourceManager.GetString("PersonalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppy Care is system that helps you to watch for your pet..
        /// </summary>
        public static string PuppyCareIs {
            get {
                return ResourceManager.GetString("PuppyCareIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Collar module will help you to monitor effectively your dog’s health state. It will control the temperature and measure the pulse of a pet to let you know how your pet feels wherever it is. Due to the GPS using you will also be able to know your pet’s location anytime..
        /// </summary>
        public static string SmartCollar {
            get {
                return ResourceManager.GetString("SmartCollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System includes apps on Android, Windows Phone and IOS..
        /// </summary>
        public static string SystemIncludes {
            get {
                return ResourceManager.GetString("SystemIncludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your Puppy Care project account.
        /// </summary>
        public static string UsePersonal {
            get {
                return ResourceManager.GetString("UsePersonal", resourceCulture);
            }
        }
    }
}
